mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS rocket"
mysql -uroot -proot -e "use rocket"
mysql -uroot -proot -e "create table data ( seq INT PRIMARY KEY AUTO_INCREMENT, poti FLOAT, light FLOAT, hall FLOAT, temp FLOAT, created TIMESTAMP DEFAULT CURRENT_TIMESTAMP)"
mysql -uroot -proot -e "insert into data(poti, light, hall, temp) values ( 0.9, 0.8, 0.49, 25.2 )"
mysql -uroot -proot -e "insert into data(poti, light, hall, temp) values ( 0.8, 0.7, 0.48, 25.1 )"